/* Reconstructed BioMenace Source Code
 * Copyright (C) 2017-2025 K1n9_Duk3
 *
 * This file is loosely based on:
 * Keen Dreams Source Code
 * Copyright (C) 2014 Javier M. Chavez
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// New file used for preparing and converting pointers to states

#include "bm_def.h"

// NOTE: These are specific to the July 1992 beta only!
// RefKeen_FillObjStatesWithDOSPointers is still implemented for all versions
// due to being called for patching, albeit being a no-op outside of the beta.

REFKEEN_NS_B

#ifdef BETA
// List of all states
extern statetype s_nullstate;
extern statetype s_badstate; // Unused
extern statetype s_snakedie1;
extern statetype s_snakedie2;
extern statetype s_snakeUNUSED1; // Unused
extern statetype s_snakestand;
extern statetype s_snakewormstand;
extern statetype s_snakestanduse;
extern statetype s_snakeUNUSED2; // Unused
extern statetype s_snakeslide;
extern statetype s_snakeshuttle;
extern statetype s_snaketeleport1;
extern statetype s_snaketeleport2;
extern statetype s_snakeuse1;
extern statetype s_snakeuse2;
extern statetype s_snakeopendoor1;
extern statetype s_snakeopendoor2;
extern statetype s_snakeduck;
extern statetype s_snakeladder;
extern statetype s_snakeclimb1;
extern statetype s_snakeclimb2;
extern statetype s_snakewalk1;
extern statetype s_snakewalk2;
extern statetype s_snakewalk3;
extern statetype s_snakewalk4;
extern statetype s_snakewormwalk1;
extern statetype s_snakewormwalk2;
extern statetype s_snakethrow1;
extern statetype s_snakethrow2;
extern statetype s_snakethrow3;
extern statetype s_snakeairthrow1;
extern statetype s_snakeairthrow2;
extern statetype s_snakeairthrow3;
extern statetype s_snakejump1;
extern statetype s_snakejump2;
extern statetype s_snakejump3;
extern statetype s_snakewormair1;
extern statetype s_snakewormair2;
extern statetype s_snakewormair3;
extern statetype s_snakewormattack;
extern statetype s_snakewormairattack;
extern statetype s_snakestandfire1;
extern statetype s_snakestandfire2;
extern statetype s_snakestandfire3;
extern statetype s_snakeairfire1;
extern statetype s_snakeairfire2;
extern statetype s_snakeairfire3;
extern statetype s_snakeduckfire1;
extern statetype s_snakeduckfire2;
extern statetype s_snakeduckfire3;
extern statetype s_snakestandautofire1;
extern statetype s_snakestandautofire2;
extern statetype s_snakeduckautofire1;
extern statetype s_snakeduckautofire2;
extern statetype s_snakeairautofire1;
extern statetype s_snakeairautofire2;
extern statetype s_score;
extern statetype s_smallexplosion1;
extern statetype s_smallexplosion2;
extern statetype s_smallexplosion3;
extern statetype s_chunk1;
extern statetype s_chunk2;
extern statetype s_chunk3;
extern statetype s_chunk4;
extern statetype s_chunkground;
extern statetype s_metalchunk1;
extern statetype s_metalchunk2;
extern statetype s_metalchunk3;
extern statetype s_metalchunk4;
extern statetype s_metalchunkground;
extern statetype s_frag1;
extern statetype s_frag2;
extern statetype s_frag3;
extern statetype s_frag4;
extern statetype s_grenadeg1;
extern statetype s_grenadeg2;
extern statetype s_grenadeg3;
extern statetype s_grenadeg4;
extern statetype s_grenadeexplosion1;
extern statetype s_grenadeexplosion2;
extern statetype s_grenadeexplosion3;
extern statetype s_grenadeexplosion4;
extern statetype s_grenadeexplosion5;
extern statetype s_grenadeexplosion6;
extern statetype s_robopalshot1;
extern statetype s_robopalshot2;
extern statetype s_explosion_a1;
extern statetype s_explosion_a2;
extern statetype s_platform;
extern statetype s_shuttle;
extern statetype s_queen1;
extern statetype s_queen2;
extern statetype s_caterpillarhead1;
extern statetype s_caterpillarhead2;
extern statetype s_caterpillarbody;
extern statetype s_cobrawalk1;
extern statetype s_cobrawalk2;
extern statetype s_cobrarun1;
extern statetype s_cobrarun2;
extern statetype s_cobraattack1;
extern statetype s_cobraattack2;
extern statetype s_cobraspit1;
extern statetype s_cobraspit2;
extern statetype s_jimstand;
extern statetype s_jimattack1;
extern statetype s_jimattack2;
extern statetype s_georgestand1;
extern statetype s_georgestand2;
extern statetype s_keenstand1;
extern statetype s_keenstand2;
extern statetype s_hostage1stand;
extern statetype s_hostage1walk;
extern statetype s_hostage2stand1;
extern statetype s_hostage2stand2;
extern statetype s_hostage3stand1;
extern statetype s_hostage3stand2;
extern statetype s_bosshead1;
extern statetype s_bosshead2;
extern statetype s_bosshead3;
extern statetype s_bossheadfade1;
extern statetype s_bossheadfade2;
extern statetype s_bossheadfade3;
extern statetype s_bossheadmetal;
extern statetype s_bonus1;
extern statetype s_bonus2;
extern statetype s_bonusrise;
extern statetype s_bug1;
extern statetype s_bug2;
extern statetype s_bee1;
extern statetype s_bee2;
extern statetype s_nymph1;
extern statetype s_nymph2;
extern statetype s_robopalwait1;
extern statetype s_robopalwait2;
extern statetype s_robopalfollow1;
extern statetype s_robopalfollow2;
extern statetype s_robopalteleport1;
extern statetype s_robopalteleport2;
extern statetype s_robopalteleport3;
extern statetype s_robopalteleport4;
extern statetype s_robopalteleport5;
extern statetype s_wormwalk1;
extern statetype s_wormwalk2;
extern statetype s_wormjump;
extern statetype s_bluedevilwalk1;
extern statetype s_bluedevilwalk2;
extern statetype s_bluedevilwalk3;
extern statetype s_bluedevilwalk4;
extern statetype s_bluedeviljump;
extern statetype s_kamikazestand1;
extern statetype s_kamikazestand2;
extern statetype s_kamikazeturn1;
extern statetype s_kamikazeturn2;
extern statetype s_kamikazewalk1;
extern statetype s_kamikazewalk2;
extern statetype s_kamikazedie1;
extern statetype s_kamikazedie2;
extern statetype s_trashbossdie;
extern statetype s_trashbossstand;
extern statetype s_trashbosswalk1;
extern statetype s_trashbosswalk2;
extern statetype s_trashbossthrow;
extern statetype s_trashcan1;
extern statetype s_trashcan2;
extern statetype s_trashcan3;
extern statetype s_trashcan4;
extern statetype s_trashapple1;
extern statetype s_trashapple2;
extern statetype s_trashapple3;
extern statetype s_trashapple4;
extern statetype s_trashbird1;
extern statetype s_trashbird2;
extern statetype s_punchystand;
extern statetype s_punchywalk1;
extern statetype s_punchywalk2;
extern statetype s_punchywalk3;
extern statetype s_punchywalk4;
extern statetype s_punchyattack1;
extern statetype s_punchyattack2;
extern statetype s_gorpceil1;
extern statetype s_gorpceil2;
extern statetype s_gorpceil3;
extern statetype s_gorpceil4;
extern statetype s_gorpwalk1;
extern statetype s_gorpwalk2;
extern statetype s_gorpwalk3;
extern statetype s_gorpwalk4;
extern statetype s_gorpfall;
extern statetype s_bigexplosion1;
extern statetype s_bigexplosion2;
extern statetype s_bigexplosion3;
extern statetype s_antwalk1;
extern statetype s_antwalk2;
extern statetype s_antwalk3;
extern statetype s_antwalk4;
extern statetype s_antattack1;
extern statetype s_antattack2;
extern statetype s_antjump;
extern statetype s_tankdie;
extern statetype s_tankstand;
extern statetype s_tankwalk1;
extern statetype s_tankwalk2;
extern statetype s_tankattack1;
extern statetype s_tankattack2;
extern statetype s_smallrocketfly;
extern statetype s_smallrocketfall;
extern statetype s_tankshot;
extern statetype s_tankshotexplode1;
extern statetype s_tankshotexplode2;
extern statetype s_smallfire1;
extern statetype s_smallfire2;
extern statetype s_smallfire3;
extern statetype s_guardstand;
extern statetype s_guardattack1;
extern statetype s_guardattack2;
extern statetype s_guardattack3;
extern statetype s_guarddie;
extern statetype s_enemyshot;
extern statetype s_explosion1;
extern statetype s_explosion2;
extern statetype s_block;
extern statetype s_blockfall;
extern statetype s_brick;
extern statetype s_brickfall;
extern statetype s_crusher;
extern statetype s_crushersink;
extern statetype s_bouncer1;
extern statetype s_bouncer2;
extern statetype s_bouncer3;
extern statetype s_bouncer4;
extern statetype s_bouncer_ground;
extern statetype s_acidmonster1;
extern statetype s_acidmonster2;
extern statetype s_acidmonster3;
extern statetype s_acid1;
extern statetype s_acid2;
extern statetype s_acidfall;
extern statetype s_acidland1;
extern statetype s_acidland2;
extern statetype s_acidland3;
extern statetype s_acidland4;
extern statetype s_spikey1;
extern statetype s_spikey2;
extern statetype s_trashtruck1;
extern statetype s_trashtruck2;
extern statetype s_turret1;
extern statetype s_turretattack1;
extern statetype s_turretattack2;
extern statetype s_turretattack3;
#endif // BETA

void RefKeen_FillObjStatesWithDOSPointers(void)
{
#ifdef BETA
	s_nullstate.compatdospointer = 0x06B4;
	s_badstate.compatdospointer = 0x06D2; // Unused, hence not defined
	s_snakedie1.compatdospointer = 0x083C;
	s_snakedie2.compatdospointer = 0x085A;
	s_snakeUNUSED1.compatdospointer = 0x0878;
	s_snakestand.compatdospointer = 0x0896;
	s_snakewormstand.compatdospointer = 0x08B4;
	s_snakestanduse.compatdospointer = 0x08D2;
	s_snakeUNUSED2.compatdospointer = 0x08F0; // Unused, hence not defined
	s_snakeslide.compatdospointer = 0x090E;
	s_snakeshuttle.compatdospointer = 0x092C;
	s_snaketeleport1.compatdospointer = 0x094A;
	s_snaketeleport2.compatdospointer = 0x0968;
	s_snakeuse1.compatdospointer = 0x0986;
	s_snakeuse2.compatdospointer = 0x09A4;
	s_snakeopendoor1.compatdospointer = 0x09C2;
	s_snakeopendoor2.compatdospointer = 0x09E0;
	s_snakeduck.compatdospointer = 0x09FE;
	s_snakeladder.compatdospointer = 0x0A1C;
	s_snakeclimb1.compatdospointer = 0x0A3A;
	s_snakeclimb2.compatdospointer = 0x0A58;
	s_snakewalk1.compatdospointer = 0x0A76;
	s_snakewalk2.compatdospointer = 0x0A94;
	s_snakewalk3.compatdospointer = 0x0AB2;
	s_snakewalk4.compatdospointer = 0x0AD0;
	s_snakewormwalk1.compatdospointer = 0x0AEE;
	s_snakewormwalk2.compatdospointer = 0x0B0C;
	s_snakethrow1.compatdospointer = 0x0B2A;
	s_snakethrow2.compatdospointer = 0x0B48;
	s_snakethrow3.compatdospointer = 0x0B66;
	s_snakeairthrow1.compatdospointer = 0x0B84;
	s_snakeairthrow2.compatdospointer = 0x0BA2;
	s_snakeairthrow3.compatdospointer = 0x0BC0;
	s_snakejump1.compatdospointer = 0x0BDE;
	s_snakejump2.compatdospointer = 0x0BFC;
	s_snakejump3.compatdospointer = 0x0C1A;
	s_snakewormair1.compatdospointer = 0x0C38;
	s_snakewormair2.compatdospointer = 0x0C56;
	s_snakewormair3.compatdospointer = 0x0C74;
	s_snakewormattack.compatdospointer = 0x0C92;
	s_snakewormairattack.compatdospointer = 0x0CB0;
	s_snakestandfire1.compatdospointer = 0x0CCE;
	s_snakestandfire2.compatdospointer = 0x0CEC;
	s_snakestandfire3.compatdospointer = 0x0D0A;
	s_snakeairfire1.compatdospointer = 0x0D28;
	s_snakeairfire2.compatdospointer = 0x0D46;
	s_snakeairfire3.compatdospointer = 0x0D64;
	s_snakeduckfire1.compatdospointer = 0x0D82;
	s_snakeduckfire2.compatdospointer = 0x0DA0;
	s_snakeduckfire3.compatdospointer = 0x0DBE;
	s_snakestandautofire1.compatdospointer = 0x0DDC;
	s_snakestandautofire2.compatdospointer = 0x0DFA;
	s_snakeduckautofire1.compatdospointer = 0x0E18;
	s_snakeduckautofire2.compatdospointer = 0x0E36;
	s_snakeairautofire1.compatdospointer = 0x0E54;
	s_snakeairautofire2.compatdospointer = 0x0E72;
	s_score.compatdospointer = 0x0FF0;
	s_smallexplosion1.compatdospointer = 0x100E;
	s_smallexplosion2.compatdospointer = 0x102C;
	s_smallexplosion3.compatdospointer = 0x104A;
	s_chunk1.compatdospointer = 0x1068;
	s_chunk2.compatdospointer = 0x1086;
	s_chunk3.compatdospointer = 0x10A4;
	s_chunk4.compatdospointer = 0x10C2;
	s_chunkground.compatdospointer = 0x10E0;
	s_metalchunk1.compatdospointer = 0x10FE;
	s_metalchunk2.compatdospointer = 0x111C;
	s_metalchunk3.compatdospointer = 0x113A;
	s_metalchunk4.compatdospointer = 0x1158;
	s_metalchunkground.compatdospointer = 0x1176;
	s_frag1.compatdospointer = 0x1194;
	s_frag2.compatdospointer = 0x11B2;
	s_frag3.compatdospointer = 0x11D0;
	s_frag4.compatdospointer = 0x11EE;
	s_grenadeg1.compatdospointer = 0x120C;
	s_grenadeg2.compatdospointer = 0x122A;
	s_grenadeg3.compatdospointer = 0x1248;
	s_grenadeg4.compatdospointer = 0x1266;
	s_grenadeexplosion1.compatdospointer = 0x1284;
	s_grenadeexplosion2.compatdospointer = 0x12A2;
	s_grenadeexplosion3.compatdospointer = 0x12C0;
	s_grenadeexplosion4.compatdospointer = 0x12DE;
	s_grenadeexplosion5.compatdospointer = 0x12FC;
	s_grenadeexplosion6.compatdospointer = 0x131A;
	s_robopalshot1.compatdospointer = 0x1338;
	s_robopalshot2.compatdospointer = 0x1356;
	s_explosion_a1.compatdospointer = 0x1374;
	s_explosion_a2.compatdospointer = 0x1392;
	s_platform.compatdospointer = 0x1556;
	s_shuttle.compatdospointer = 0x1574;
	s_queen1.compatdospointer = 0x1592;
	s_queen2.compatdospointer = 0x15B0;
	s_caterpillarhead1.compatdospointer = 0x15CE;
	s_caterpillarhead2.compatdospointer = 0x15EC;
	s_caterpillarbody.compatdospointer = 0x160A;
	s_cobrawalk1.compatdospointer = 0x1669;
	s_cobrawalk2.compatdospointer = 0x1687;
	s_cobrarun1.compatdospointer = 0x16A5;
	s_cobrarun2.compatdospointer = 0x16C3;
	s_cobraattack1.compatdospointer = 0x16E1;
	s_cobraattack2.compatdospointer = 0x16FF;
	s_cobraspit1.compatdospointer = 0x171D;
	s_cobraspit2.compatdospointer = 0x173B;
	s_jimstand.compatdospointer = 0x1759;
	s_jimattack1.compatdospointer = 0x1777;
	s_jimattack2.compatdospointer = 0x1795;
	s_georgestand1.compatdospointer = 0x17B3;
	s_georgestand2.compatdospointer = 0x17D1;
	s_keenstand1.compatdospointer = 0x17EF;
	s_keenstand2.compatdospointer = 0x180D;
	s_hostage1stand.compatdospointer = 0x182B;
	s_hostage1walk.compatdospointer = 0x1849;
	s_hostage2stand1.compatdospointer = 0x1867;
	s_hostage2stand2.compatdospointer = 0x1885;
	s_hostage3stand1.compatdospointer = 0x18A3;
	s_hostage3stand2.compatdospointer = 0x18C1;
	s_bosshead1.compatdospointer = 0x18DF;
	s_bosshead2.compatdospointer = 0x18FD;
	s_bosshead3.compatdospointer = 0x191B;
	s_bossheadfade1.compatdospointer = 0x1939;
	s_bossheadfade2.compatdospointer = 0x1957;
	s_bossheadfade3.compatdospointer = 0x1975;
	s_bossheadmetal.compatdospointer = 0x1993;
	s_bonus1.compatdospointer = 0x19BC;
	s_bonus2.compatdospointer = 0x19DA;
	s_bonusrise.compatdospointer = 0x19F8;
	s_bug1.compatdospointer = 0x1A5E;
	s_bug2.compatdospointer = 0x1A7C;
	s_bee1.compatdospointer = 0x1A9A;
	s_bee2.compatdospointer = 0x1AB8;
	s_nymph1.compatdospointer = 0x1AD6;
	s_nymph2.compatdospointer = 0x1AF4;
	s_robopalwait1.compatdospointer = 0x1B12;
	s_robopalwait2.compatdospointer = 0x1B30;
	s_robopalfollow1.compatdospointer = 0x1B4E;
	s_robopalfollow2.compatdospointer = 0x1B6C;
	s_robopalteleport1.compatdospointer = 0x1B8A;
	s_robopalteleport2.compatdospointer = 0x1BA8;
	s_robopalteleport3.compatdospointer = 0x1BC6;
	s_robopalteleport4.compatdospointer = 0x1BE4;
	s_robopalteleport5.compatdospointer = 0x1C02;
	s_wormwalk1.compatdospointer = 0x1C20;
	s_wormwalk2.compatdospointer = 0x1C3E;
	s_wormjump.compatdospointer = 0x1C5C;
	s_bluedevilwalk1.compatdospointer = 0x1C7A;
	s_bluedevilwalk2.compatdospointer = 0x1C98;
	s_bluedevilwalk3.compatdospointer = 0x1CB6;
	s_bluedevilwalk4.compatdospointer = 0x1CD4;
	s_bluedeviljump.compatdospointer = 0x1CF2;
	s_kamikazestand1.compatdospointer = 0x1D10;
	s_kamikazestand2.compatdospointer = 0x1D2E;
	s_kamikazeturn1.compatdospointer = 0x1D4C;
	s_kamikazeturn2.compatdospointer = 0x1D6A;
	s_kamikazewalk1.compatdospointer = 0x1D88;
	s_kamikazewalk2.compatdospointer = 0x1DA6;
	s_kamikazedie1.compatdospointer = 0x1DC4;
	s_kamikazedie2.compatdospointer = 0x1DE2;
	s_trashbossdie.compatdospointer = 0x1E00;
	s_trashbossstand.compatdospointer = 0x1E1E;
	s_trashbosswalk1.compatdospointer = 0x1E3C;
	s_trashbosswalk2.compatdospointer = 0x1E5A;
	s_trashbossthrow.compatdospointer = 0x1E78;
	s_trashcan1.compatdospointer = 0x1E96;
	s_trashcan2.compatdospointer = 0x1EB4;
	s_trashcan3.compatdospointer = 0x1ED2;
	s_trashcan4.compatdospointer = 0x1EF0;
	s_trashapple1.compatdospointer = 0x1F0E;
	s_trashapple2.compatdospointer = 0x1F2C;
	s_trashapple3.compatdospointer = 0x1F4A;
	s_trashapple4.compatdospointer = 0x1F68;
	s_trashbird1.compatdospointer = 0x1F86;
	s_trashbird2.compatdospointer = 0x1FA4;
	s_punchystand.compatdospointer = 0x1FC2;
	s_punchywalk1.compatdospointer = 0x1FE0;
	s_punchywalk2.compatdospointer = 0x1FFE;
	s_punchywalk3.compatdospointer = 0x201C;
	s_punchywalk4.compatdospointer = 0x203A;
	s_punchyattack1.compatdospointer = 0x2058;
	s_punchyattack2.compatdospointer = 0x2076;
	s_gorpceil1.compatdospointer = 0x2094;
	s_gorpceil2.compatdospointer = 0x20B2;
	s_gorpceil3.compatdospointer = 0x20D0;
	s_gorpceil4.compatdospointer = 0x20EE;
	s_gorpwalk1.compatdospointer = 0x210C;
	s_gorpwalk2.compatdospointer = 0x212A;
	s_gorpwalk3.compatdospointer = 0x2148;
	s_gorpwalk4.compatdospointer = 0x2166;
	s_gorpfall.compatdospointer = 0x2184;
	s_bigexplosion1.compatdospointer = 0x21A2;
	s_bigexplosion2.compatdospointer = 0x21C0;
	s_bigexplosion3.compatdospointer = 0x21DE;
	s_antwalk1.compatdospointer = 0x21FC;
	s_antwalk2.compatdospointer = 0x221A;
	s_antwalk3.compatdospointer = 0x2238;
	s_antwalk4.compatdospointer = 0x2256;
	s_antattack1.compatdospointer = 0x2274;
	s_antattack2.compatdospointer = 0x2292;
	s_antjump.compatdospointer = 0x22B0;
	s_tankdie.compatdospointer = 0x22CE;
	s_tankstand.compatdospointer = 0x22EC;
	s_tankwalk1.compatdospointer = 0x230A;
	s_tankwalk2.compatdospointer = 0x2328;
	s_tankattack1.compatdospointer = 0x2346;
	s_tankattack2.compatdospointer = 0x2364;
	s_smallrocketfly.compatdospointer = 0x2382;
	s_smallrocketfall.compatdospointer = 0x23A0;
	s_tankshot.compatdospointer = 0x23BE;
	s_tankshotexplode1.compatdospointer = 0x23DC;
	s_tankshotexplode2.compatdospointer = 0x23FA;
	s_smallfire1.compatdospointer = 0x2418;
	s_smallfire2.compatdospointer = 0x2436;
	s_smallfire3.compatdospointer = 0x2454;
	s_guardstand.compatdospointer = 0x2472;
	s_guardattack1.compatdospointer = 0x2490;
	s_guardattack2.compatdospointer = 0x24AE;
	s_guardattack3.compatdospointer = 0x24CC;
	s_guarddie.compatdospointer = 0x24EA;
	s_enemyshot.compatdospointer = 0x2508;
	s_explosion1.compatdospointer = 0x2526;
	s_explosion2.compatdospointer = 0x2544;
	s_block.compatdospointer = 0x2562;
	s_blockfall.compatdospointer = 0x2580;
	s_brick.compatdospointer = 0x259E;
	s_brickfall.compatdospointer = 0x25BC;
	s_crusher.compatdospointer = 0x25DC;
	s_crushersink.compatdospointer = 0x25FA;
	s_bouncer1.compatdospointer = 0x2618;
	s_bouncer2.compatdospointer = 0x2636;
	s_bouncer3.compatdospointer = 0x2654;
	s_bouncer4.compatdospointer = 0x2672;
	s_bouncer_ground.compatdospointer = 0x2690;
	s_acidmonster1.compatdospointer = 0x26AE;
	s_acidmonster2.compatdospointer = 0x26CC;
	s_acidmonster3.compatdospointer = 0x26EA;
	s_acid1.compatdospointer = 0x2708;
	s_acid2.compatdospointer = 0x2726;
	s_acidfall.compatdospointer = 0x2744;
	s_acidland1.compatdospointer = 0x2762;
	s_acidland2.compatdospointer = 0x2780;
	s_acidland3.compatdospointer = 0x279E;
	s_acidland4.compatdospointer = 0x27BC;
	s_spikey1.compatdospointer = 0x27DA;
	s_spikey2.compatdospointer = 0x27F8;
	s_trashtruck1.compatdospointer = 0x2816;
	s_trashtruck2.compatdospointer = 0x2834;
	s_turret1.compatdospointer = 0x2852;
	s_turretattack1.compatdospointer = 0x2870;
	s_turretattack2.compatdospointer = 0x288E;
	s_turretattack3.compatdospointer = 0x28AC;
#endif // BETA
}

#ifdef BETA
statetype *RefKeen_GetObjStatePtrFromDOSPointer(uint_fast32_t dosptr)
{
	switch (dosptr)
	{
	case 0x06B4: return &s_nullstate;
//	case 0x06D2: return &s_badstate; // Unused, hence not defined
	case 0x083C: return &s_snakedie1;
	case 0x085A: return &s_snakedie2;
	case 0x0878: return &s_snakeUNUSED1;
	case 0x0896: return &s_snakestand;
	case 0x08B4: return &s_snakewormstand;
	case 0x08D2: return &s_snakestanduse;
	case 0x08F0: return &s_snakeUNUSED2; // Unused, hence not defined
	case 0x090E: return &s_snakeslide;
	case 0x092C: return &s_snakeshuttle;
	case 0x094A: return &s_snaketeleport1;
	case 0x0968: return &s_snaketeleport2;
	case 0x0986: return &s_snakeuse1;
	case 0x09A4: return &s_snakeuse2;
	case 0x09C2: return &s_snakeopendoor1;
	case 0x09E0: return &s_snakeopendoor2;
	case 0x09FE: return &s_snakeduck;
	case 0x0A1C: return &s_snakeladder;
	case 0x0A3A: return &s_snakeclimb1;
	case 0x0A58: return &s_snakeclimb2;
	case 0x0A76: return &s_snakewalk1;
	case 0x0A94: return &s_snakewalk2;
	case 0x0AB2: return &s_snakewalk3;
	case 0x0AD0: return &s_snakewalk4;
	case 0x0AEE: return &s_snakewormwalk1;
	case 0x0B0C: return &s_snakewormwalk2;
	case 0x0B2A: return &s_snakethrow1;
	case 0x0B48: return &s_snakethrow2;
	case 0x0B66: return &s_snakethrow3;
	case 0x0B84: return &s_snakeairthrow1;
	case 0x0BA2: return &s_snakeairthrow2;
	case 0x0BC0: return &s_snakeairthrow3;
	case 0x0BDE: return &s_snakejump1;
	case 0x0BFC: return &s_snakejump2;
	case 0x0C1A: return &s_snakejump3;
	case 0x0C38: return &s_snakewormair1;
	case 0x0C56: return &s_snakewormair2;
	case 0x0C74: return &s_snakewormair3;
	case 0x0C92: return &s_snakewormattack;
	case 0x0CB0: return &s_snakewormairattack;
	case 0x0CCE: return &s_snakestandfire1;
	case 0x0CEC: return &s_snakestandfire2;
	case 0x0D0A: return &s_snakestandfire3;
	case 0x0D28: return &s_snakeairfire1;
	case 0x0D46: return &s_snakeairfire2;
	case 0x0D64: return &s_snakeairfire3;
	case 0x0D82: return &s_snakeduckfire1;
	case 0x0DA0: return &s_snakeduckfire2;
	case 0x0DBE: return &s_snakeduckfire3;
	case 0x0DDC: return &s_snakestandautofire1;
	case 0x0DFA: return &s_snakestandautofire2;
	case 0x0E18: return &s_snakeduckautofire1;
	case 0x0E36: return &s_snakeduckautofire2;
	case 0x0E54: return &s_snakeairautofire1;
	case 0x0E72: return &s_snakeairautofire2;
	case 0x0FF0: return &s_score;
	case 0x100E: return &s_smallexplosion1;
	case 0x102C: return &s_smallexplosion2;
	case 0x104A: return &s_smallexplosion3;
	case 0x1068: return &s_chunk1;
	case 0x1086: return &s_chunk2;
	case 0x10A4: return &s_chunk3;
	case 0x10C2: return &s_chunk4;
	case 0x10E0: return &s_chunkground;
	case 0x10FE: return &s_metalchunk1;
	case 0x111C: return &s_metalchunk2;
	case 0x113A: return &s_metalchunk3;
	case 0x1158: return &s_metalchunk4;
	case 0x1176: return &s_metalchunkground;
	case 0x1194: return &s_frag1;
	case 0x11B2: return &s_frag2;
	case 0x11D0: return &s_frag3;
	case 0x11EE: return &s_frag4;
	case 0x120C: return &s_grenadeg1;
	case 0x122A: return &s_grenadeg2;
	case 0x1248: return &s_grenadeg3;
	case 0x1266: return &s_grenadeg4;
	case 0x1284: return &s_grenadeexplosion1;
	case 0x12A2: return &s_grenadeexplosion2;
	case 0x12C0: return &s_grenadeexplosion3;
	case 0x12DE: return &s_grenadeexplosion4;
	case 0x12FC: return &s_grenadeexplosion5;
	case 0x131A: return &s_grenadeexplosion6;
	case 0x1338: return &s_robopalshot1;
	case 0x1356: return &s_robopalshot2;
	case 0x1374: return &s_explosion_a1;
	case 0x1392: return &s_explosion_a2;
	case 0x1556: return &s_platform;
	case 0x1574: return &s_shuttle;
	case 0x1592: return &s_queen1;
	case 0x15B0: return &s_queen2;
	case 0x15CE: return &s_caterpillarhead1;
	case 0x15EC: return &s_caterpillarhead2;
	case 0x160A: return &s_caterpillarbody;
	case 0x1669: return &s_cobrawalk1;
	case 0x1687: return &s_cobrawalk2;
	case 0x16A5: return &s_cobrarun1;
	case 0x16C3: return &s_cobrarun2;
	case 0x16E1: return &s_cobraattack1;
	case 0x16FF: return &s_cobraattack2;
	case 0x171D: return &s_cobraspit1;
	case 0x173B: return &s_cobraspit2;
	case 0x1759: return &s_jimstand;
	case 0x1777: return &s_jimattack1;
	case 0x1795: return &s_jimattack2;
	case 0x17B3: return &s_georgestand1;
	case 0x17D1: return &s_georgestand2;
	case 0x17EF: return &s_keenstand1;
	case 0x180D: return &s_keenstand2;
	case 0x182B: return &s_hostage1stand;
	case 0x1849: return &s_hostage1walk;
	case 0x1867: return &s_hostage2stand1;
	case 0x1885: return &s_hostage2stand2;
	case 0x18A3: return &s_hostage3stand1;
	case 0x18C1: return &s_hostage3stand2;
	case 0x18DF: return &s_bosshead1;
	case 0x18FD: return &s_bosshead2;
	case 0x191B: return &s_bosshead3;
	case 0x1939: return &s_bossheadfade1;
	case 0x1957: return &s_bossheadfade2;
	case 0x1975: return &s_bossheadfade3;
	case 0x1993: return &s_bossheadmetal;
	case 0x19BC: return &s_bonus1;
	case 0x19DA: return &s_bonus2;
	case 0x19F8: return &s_bonusrise;
	case 0x1A5E: return &s_bug1;
	case 0x1A7C: return &s_bug2;
	case 0x1A9A: return &s_bee1;
	case 0x1AB8: return &s_bee2;
	case 0x1AD6: return &s_nymph1;
	case 0x1AF4: return &s_nymph2;
	case 0x1B12: return &s_robopalwait1;
	case 0x1B30: return &s_robopalwait2;
	case 0x1B4E: return &s_robopalfollow1;
	case 0x1B6C: return &s_robopalfollow2;
	case 0x1B8A: return &s_robopalteleport1;
	case 0x1BA8: return &s_robopalteleport2;
	case 0x1BC6: return &s_robopalteleport3;
	case 0x1BE4: return &s_robopalteleport4;
	case 0x1C02: return &s_robopalteleport5;
	case 0x1C20: return &s_wormwalk1;
	case 0x1C3E: return &s_wormwalk2;
	case 0x1C5C: return &s_wormjump;
	case 0x1C7A: return &s_bluedevilwalk1;
	case 0x1C98: return &s_bluedevilwalk2;
	case 0x1CB6: return &s_bluedevilwalk3;
	case 0x1CD4: return &s_bluedevilwalk4;
	case 0x1CF2: return &s_bluedeviljump;
	case 0x1D10: return &s_kamikazestand1;
	case 0x1D2E: return &s_kamikazestand2;
	case 0x1D4C: return &s_kamikazeturn1;
	case 0x1D6A: return &s_kamikazeturn2;
	case 0x1D88: return &s_kamikazewalk1;
	case 0x1DA6: return &s_kamikazewalk2;
	case 0x1DC4: return &s_kamikazedie1;
	case 0x1DE2: return &s_kamikazedie2;
	case 0x1E00: return &s_trashbossdie;
	case 0x1E1E: return &s_trashbossstand;
	case 0x1E3C: return &s_trashbosswalk1;
	case 0x1E5A: return &s_trashbosswalk2;
	case 0x1E78: return &s_trashbossthrow;
	case 0x1E96: return &s_trashcan1;
	case 0x1EB4: return &s_trashcan2;
	case 0x1ED2: return &s_trashcan3;
	case 0x1EF0: return &s_trashcan4;
	case 0x1F0E: return &s_trashapple1;
	case 0x1F2C: return &s_trashapple2;
	case 0x1F4A: return &s_trashapple3;
	case 0x1F68: return &s_trashapple4;
	case 0x1F86: return &s_trashbird1;
	case 0x1FA4: return &s_trashbird2;
	case 0x1FC2: return &s_punchystand;
	case 0x1FE0: return &s_punchywalk1;
	case 0x1FFE: return &s_punchywalk2;
	case 0x201C: return &s_punchywalk3;
	case 0x203A: return &s_punchywalk4;
	case 0x2058: return &s_punchyattack1;
	case 0x2076: return &s_punchyattack2;
	case 0x2094: return &s_gorpceil1;
	case 0x20B2: return &s_gorpceil2;
	case 0x20D0: return &s_gorpceil3;
	case 0x20EE: return &s_gorpceil4;
	case 0x210C: return &s_gorpwalk1;
	case 0x212A: return &s_gorpwalk2;
	case 0x2148: return &s_gorpwalk3;
	case 0x2166: return &s_gorpwalk4;
	case 0x2184: return &s_gorpfall;
	case 0x21A2: return &s_bigexplosion1;
	case 0x21C0: return &s_bigexplosion2;
	case 0x21DE: return &s_bigexplosion3;
	case 0x21FC: return &s_antwalk1;
	case 0x221A: return &s_antwalk2;
	case 0x2238: return &s_antwalk3;
	case 0x2256: return &s_antwalk4;
	case 0x2274: return &s_antattack1;
	case 0x2292: return &s_antattack2;
	case 0x22B0: return &s_antjump;
	case 0x22CE: return &s_tankdie;
	case 0x22EC: return &s_tankstand;
	case 0x230A: return &s_tankwalk1;
	case 0x2328: return &s_tankwalk2;
	case 0x2346: return &s_tankattack1;
	case 0x2364: return &s_tankattack2;
	case 0x2382: return &s_smallrocketfly;
	case 0x23A0: return &s_smallrocketfall;
	case 0x23BE: return &s_tankshot;
	case 0x23DC: return &s_tankshotexplode1;
	case 0x23FA: return &s_tankshotexplode2;
	case 0x2418: return &s_smallfire1;
	case 0x2436: return &s_smallfire2;
	case 0x2454: return &s_smallfire3;
	case 0x2472: return &s_guardstand;
	case 0x2490: return &s_guardattack1;
	case 0x24AE: return &s_guardattack2;
	case 0x24CC: return &s_guardattack3;
	case 0x24EA: return &s_guarddie;
	case 0x2508: return &s_enemyshot;
	case 0x2526: return &s_explosion1;
	case 0x2544: return &s_explosion2;
	case 0x2562: return &s_block;
	case 0x2580: return &s_blockfall;
	case 0x259E: return &s_brick;
	case 0x25BC: return &s_brickfall;
	case 0x25DC: return &s_crusher;
	case 0x25FA: return &s_crushersink;
	case 0x2618: return &s_bouncer1;
	case 0x2636: return &s_bouncer2;
	case 0x2654: return &s_bouncer3;
	case 0x2672: return &s_bouncer4;
	case 0x2690: return &s_bouncer_ground;
	case 0x26AE: return &s_acidmonster1;
	case 0x26CC: return &s_acidmonster2;
	case 0x26EA: return &s_acidmonster3;
	case 0x2708: return &s_acid1;
	case 0x2726: return &s_acid2;
	case 0x2744: return &s_acidfall;
	case 0x2762: return &s_acidland1;
	case 0x2780: return &s_acidland2;
	case 0x279E: return &s_acidland3;
	case 0x27BC: return &s_acidland4;
	case 0x27DA: return &s_spikey1;
	case 0x27F8: return &s_spikey2;
	case 0x2816: return &s_trashtruck1;
	case 0x2834: return &s_trashtruck2;
	case 0x2852: return &s_turret1;
	case 0x2870: return &s_turretattack1;
	case 0x288E: return &s_turretattack2;
	case 0x28AC: return &s_turretattack3;
	}
	return NULL;
}
#endif // BETA

REFKEEN_NS_E
