.PHONY: clean
all:
	$(MAKE) all -C cat3d
	$(MAKE) all -C catabyss
	$(MAKE) all -C catarm
	$(MAKE) all -C catapoc
clean:
	$(MAKE) clean -C cat3d
	$(MAKE) clean -C catabyss
	$(MAKE) clean -C catarm
	$(MAKE) clean -C catapoc
