#ifndef BE_GAMESTR_H
#define BE_GAMESTR_H

#ifdef REFKEEN_HAS_VER_KDREAMS
#define BE_STR_GAMEVER_KDREAMSE100 "kdreamse100"
#define BE_STR_GAMEVER_KDREAMSC100 "kdreamsc100"
#define BE_STR_GAMEVER_KDREAMSE113 "kdreamse113"
#define BE_STR_GAMEVER_KDREAMSC105 "kdreamsc105"
#define BE_STR_GAMEVER_KDREAMSE193 "kdreamse193"
#define BE_STR_GAMEVER_KDREAMSE120 "kdreamse120"
#define BE_STR_GAMEVER_KDREAMS2015 "kdreams2015"
#endif
#ifdef REFKEEN_HAS_VER_CAT3D
#define BE_STR_GAMEVER_CAT3D100 "cat3d100"
#define BE_STR_GAMEVER_CAT3D122 "cat3d122"
#endif
#ifdef REFKEEN_HAS_VER_CATABYSS
#define BE_STR_GAMEVER_CATABYSS113 "catabyss113"
#define BE_STR_GAMEVER_CATABYSS124 "catabyss124"
#endif
#ifdef REFKEEN_HAS_VER_CATARM
#define BE_STR_GAMEVER_CATARM102 "catarm102"
#endif
#ifdef REFKEEN_HAS_VER_CATAPOC
#define BE_STR_GAMEVER_CATAPOC101 "catapoc101"
#endif
#ifdef REFKEEN_HAS_VER_WL1AP10
#define BE_STR_GAMEVER_WL1AP10 "wl1ap10"
#endif
#ifdef REFKEEN_HAS_VER_WL1AP11
#define BE_STR_GAMEVER_WL1AP11 "wl1ap11"
#endif

#endif // BE_GAMESTR_H
